"""
src/dashboard/pages/03_reports.py
Reports page — LLM-as-a-judge validated reports.
"""
import streamlit as st
from src.dashboard.components.api_client import get_reports, run_agent

st.set_page_config(page_title="Reports", page_icon="📄", layout="wide")

if "token" not in st.session_state:
    st.warning("Please login from the main page.")
    st.stop()

st.title("📄 Generated Reports")
st.caption(
    "Reports generated by ReporterAgent and validated by LLM-as-a-judge. "
    "Only reports with overall score ≥ 0.80 are approved."
)

# Generate report button
col1, col2 = st.columns([1, 3])
with col1:
    if st.button("🤖 Generate New Report", type="primary", use_container_width=True):
        with st.spinner("Generating report via Agent..."):
            result = run_agent(
                task="report",
                metrics={"rmse": 0.18, "consecutive_periods": 6, "mae": 0.12},
            )
        if result.get("status") == "completed":
            st.success("Report generated!")
            st.rerun()
        else:
            st.error("Report generation failed.")

st.divider()

reports = get_reports()

if not reports:
    st.info("No reports yet. Click 'Generate New Report' or run an agent analysis.")
else:
    for report in reports:
        faith = report.get("faithfulness_score", 0)
        rel = report.get("relevance_score", 0)
        quality = report.get("_quality_score", max(faith, rel))
        approved = report.get("is_validated", False) or quality >= 0.8

        quality_icon = "✅" if approved else "⚠️"

        with st.expander(
            f"{quality_icon} {report.get('title', 'Untitled')} | "
            f"Quality: {quality:.0%}",
            expanded=True,
        ):
            # Quality scores
            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Faithfulness", f"{faith:.0%}",
                        help="Are all claims grounded in data?")
            col2.metric("Relevance", f"{rel:.0%}",
                        help="Does it address the right question?")
            col3.metric("Overall", f"{quality:.0%}")
            col4.metric("Approved", "Yes ✅" if approved else "No ⚠️")

            st.markdown("**Executive Summary:**")
            st.write(report.get("summary", "No summary"))

            # Findings
            findings = report.get("findings", [])
            if findings:
                st.markdown("**Findings:**")
                for f in findings:
                    severity = f.get("severity", "low")
                    icons = {
                        "critical": "🔴",
                        "high": "🟠",
                        "medium": "🟡",
                        "low": "🟢"
                    }
                    icon = icons.get(severity, "⚪")
                    st.write(
                        f"{icon} **{f.get('finding')}** — "
                        f"*Evidence: {f.get('evidence')}*"
                    )

            # Recommendations
            recs = report.get("recommendations", [])
            if recs:
                st.markdown("**Recommendations:**")
                for r in recs:
                    priority = r.get("priority", "long_term")
                    icons = {
                        "immediate": "🔴",
                        "short_term": "🟡",
                        "long_term": "🟢"
                    }
                    icon = icons.get(priority, "⚪")
                    st.write(
                        f"{icon} **{r.get('action')}** — "
                        f"{r.get('rationale')}"
                    )

            eval_data = report.get("_evaluation", {})
            if eval_data.get("issues"):
                st.warning(
                    f"LLM Judge issues: {' | '.join(eval_data['issues'])}"
                )

            st.caption(
                f"ID: {str(report.get('id', ''))[:8]}... | "
                f"Type: {report.get('report_type', 'N/A')} | "
                f"{str(report.get('created_at', ''))[:19]}"
            )
