"""
src/dashboard/pages/03_reports.py
Reports page — generated by LLM Agent Reporter.
"""
import streamlit as st
from src.dashboard.components.api_client import get_reports

st.set_page_config(page_title="Reports", page_icon="📄", layout="wide")

if "token" not in st.session_state:
    st.warning("Please login from the main page.")
    st.stop()

st.title("Generated Reports")
st.caption("Reports generated by the Agent Reporter with LLM-as-a-judge validation")

reports = get_reports()

if not reports:
    st.info("No reports yet. Run an agent analysis to generate reports.")
else:
    for report in reports:
        faith = report.get("faithfulness_score", 0)
        rel = report.get("relevance_score", 0)

        with st.expander(
            f"📄 {report.get('title', 'Untitled')} — "
            f"Faithfulness: {faith:.0%} | Relevance: {rel:.0%}",
            expanded=True,
        ):
            col1, col2, col3 = st.columns(3)
            col1.metric("Faithfulness", f"{faith:.0%}")
            col2.metric("Relevance", f"{rel:.0%}")
            col3.metric("Validated", "Yes" if report.get("is_validated") else "No")

            st.markdown("**Summary:**")
            st.write(report.get("summary", "No summary"))

            findings = report.get("findings", [])
            if findings:
                st.markdown("**Findings:**")
                for f in findings:
                    severity_icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(
                        f.get("severity", "low"), "⚪"
                    )
                    st.write(
                        f"{severity_icon} **{f.get('finding')}** — "
                        f"Evidence: {f.get('evidence')}"
                    )

            recs = report.get("recommendations", [])
            if recs:
                st.markdown("**Recommendations:**")
                for r in recs:
                    priority_icon = {"immediate": "🔴", "short_term": "🟡", "long_term": "🟢"}.get(
                        r.get("priority", "long_term"), "⚪"
                    )
                    st.write(
                        f"{priority_icon} **{r.get('action')}** — "
                        f"{r.get('rationale')}"
                    )

            st.caption(f"Report ID: {report['id'][:8]}... | {report.get('created_at', 'N/A')[:19]}")
